language: node_js
node_js:
    - "5"
addons:
  chrome: stable
cache:
    directories:
        - node_modules
        - typings
install:
    - npm install
    - npm run typings:install
script:
    - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
