language: node_js
node_js:
    - "5"
cache:
    directories:
        - node_modules
        - typings
before_install:
    - export CHROME_BIN=/usr/bin/google-chrome
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm install
    - npm run typings:install
script:
    - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
